---
- name: Install OpenJDK 1.7.0, 1.8.0 and 1.11
  yum:
    name:
      - java-1.7.0-openjdk-devel
      - java-1.8.0-openjdk-devel
      - java-11-openjdk-devel
    state: present
  become: true

- name: Set Java path
  set_fact:
    java_path: /usr/lib/jvm/java-1.8.0-openjdk
